---
title: "LA Histogram Options for DDM"
author: "Summer Clay"
date: "February 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Package import
library(tidyverse)
library(forcats)
library(ggplot2)
library(RColorBrewer)

# Create ggplot2 theme for graphs 
theme_apa <- theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
                axis.line=element_line(),
        text=element_text(family='Times'),
        legend.title=element_blank())
```


### Loss Aversion Histograms:


```{r one_LA_data, echo = FALSE, results = FALSE}
## Bring in data
LA_data <- read.csv("C:/Users/Summer/Desktop/DDM Traces for figures/DDM LA data.csv", col.names = c("Subject", "LA"))

```


```{r one_LA_hist, echo = FALSE, error = FALSE, message = FALSE, warning = FALSE}
## LA plot data 
LA_plot <- ggplot(data = LA_data, aes(x = as.numeric(LA))) + 
  theme_apa 

# LA histogram with large bins
LA_hist_lb <- LA_plot + 
  geom_histogram(binwidth = 0.5, fill = "light blue", color = "black", alpha = 0.75)  + 
  ylim(0, 30) + scale_x_continuous(breaks = seq(0.0, 5, 0.5), limits = c(-0.0, 5.5)) + 
  labs(
    x = "Loss Aversion (lambda)",
    y = "Frequency")

LA_hist_lb + geom_segment(x = 1.39, y = -1.0, xend = 1.39, yend = 31, color = "#999999") + geom_segment(x = 2.69, y = -1.0, xend = 2.69, yend = 31, color = "#999999")

# LA histogram with small bins
LA_hist_sb <- LA_plot + 
  geom_histogram(binwidth = 0.1, fill = "light blue", color = "black", alpha = 0.75)  + 
  ylim(0, 10) + scale_x_continuous(breaks = seq(0.0, 5, 0.5), limits = c(-0.0, 5.5)) + 
  labs(
    x = "Loss Aversion (lambda)",
    y = "Frequency")

LA_hist_sb + geom_segment(x = 1.39, y = -.3, xend = 1.39, yend = 10.3, color = "#999999") + geom_segment(x = 2.69, y = -0.3, xend = 2.69, yend = 10.3, color = "#999999")
```